export const SHOP_ACTIONS = {
    ADD_TO_CART: "ADD_TO_CART",
    REMOVE_FROM_CART: "REMOVE_FROM_CART",
    SET_IS_PRODUCTS_LOADING: "SET_IS_PRODUCTS_LOADING",
    SET_IS_MAKING_ORDER: "SET_IS_MAKING_ORDER",
    SET_PRODUCTS: "SET_PRODUCTS",
    INCREASE_CART_TOTAL: "INCREASE_CART_TOTAL",
    DECREASE_CART_TOTAL: "DECREASE_CART_TOTAL",
    RESET_CART: "RESET_CART",
    RESET_CART_TOTAL: "RESET_CART_TOTAL",
    SET_HAS_MADE_ORDER: "SET_HAS_MADE_ORDER",
  };
  